# Generated by Django 4.0.1 on 2022-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookIndex', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=100)),
                ('Bookstate', models.CharField(max_length=100)),
                ('LendDate', models.DateField()),
                ('ReturnDate', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientIndex', models.AutoField(primary_key=True, serialize=False)),
                ('ClientId', models.CharField(max_length=100)),
            ],
        ),
    ]
